### ISSUE TITLE
issues?

### ISSUE THREAD

**Issue by baradhili** [akivajp/dnsmasq-webconf#2]
Getting this..

> python ~/git/dnsmasq-webconf/app/index.py 8080 --hosts /etc/hosts
> [2020/12/22 15:01:50 lpu __init__.py:<module>:32] Initialized LPU
> [2020/12/22 15:01:50 lpu __init__.py:<module>:41] Cython is not available
> Traceback (most recent call last):
>   File "/home/bret/git/dnsmasq-webconf/app/index.py", line 282, in <module>
>     dprint(__name__)
>   File "/home/bret/git/dnsmasq-webconf/app/index.py", line 25, in dprint
>     logger.debug_print(pprint.pformat(obj), offset=1)
>   File "lpu/common/logging.py", line 289, in lpu.common.logging.CustomLogger.debug_print
> ValueError: call stack is not deep enough
> 

Python is v3.5.3 on a Raspberry Pi.. Cython is installed via apt

**Comment by akivajp** [comment]
Sorry for the late reply. Cython and the package "lpu" are no more needed.
